### ISSUE TITLE
Not able to reproduce the Results

### ISSUE THREAD

**Issue by neerajbattan** [Sunnydreamrain/IndRNN_pytorch#4]
Hi,

Thanks for the wonderful work. I tried to reproduce the results for Action Recognition task on NTU RGB+D dataset on the subject split, by running the provided command.
- python -u Indrnn_action_train.py --dropout 0.25 --use_weightdecay_nohiddenW
The maximum Accuracy I am able to reach is 72.48%.
Is there something needed to be changed to get the desired results?

**Comment by Sunnydreamrain** [comment]
Hi,

Maybe add another option  --pThre 50. But the one you used should work. I also received emails from others when they achieved the desired results.   
Could you please check check your log with the one I uploaded.  
https://github.com/Sunnydreamrain/IndRNN_pytorch/blob/master/action_recognition/logindrnn_6layers_512_drop25_bs128.log

**Comment by neerajbattan** [comment]
Hi,

Thank you for the quick reply, can you please share your test and train split for view-specific and subject-specific partitions.

In my log file the data splits are:

Dataset train size, test size : (31622 1665) : (TRAIN AND VALIDATION SPLITS)
Dataset size : (23291)      (TEST SPLIT)

and in the one you shared are:

Dataset train size, test size :  (38086, 2005) : (TRAIN AND VALIDATION SPLITS)
Dataset size : (16487)       (TEST SPLIT)

**Comment by Sunnydreamrain** [comment]
Hi,

Your split should be wrong. As shown in the paper, pp. 5, (CS) "For this evaluation, the training and testing sets have 40320 and 16560 samples, respectively." (CV) "For this evaluation, the training and testing sets have 37920 and 18960samples, respectively."  
Since the skeletons of some samples are missing, the ones used are slightly less than those specified in the paper.
